name = "JQ"
uuid = "8cdd95e2-f406-42a8-a750-e8b0fe427919"
authors = ["Tanmay Mohapatra <tanmaykm@gmail.com>"]
version = "0.1.0"
keywords = ["jq"]
license = "MIT"

[deps]
jq_jll = "f8f80db2-c0ba-59e9-a5c3-38d72e3c5ac2"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"

[compat]
julia = "1.6"
jq_jll = "1.6"
JSON = "0.20, 0.21"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
